### ISSUE TITLE
TypeError when starting new game

### ISSUE THREAD

**Issue by sanderploegsma** [hubot-archive/hubot-2048#1]
When I'm starting a new game, the script throws a TypeError caused by a circular reference when trying to create a JSON object. 

Full stacktrace:

```
[Thu Jun 18 2015 11:22:09 GMT+0200 (CEST)] ERROR TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Brain.<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot-redis-brain/src/redis-brain.coffee:75:5, <js>:61:56)
  at Brain.emit (events.js:95:17)
  at Brain.save (/Users/sander/dev/florriebot/node_modules/hubot/src/brain.coffee:54:5, <js>:52:19)
  at TextListener.callback (/Users/sander/dev/florriebot/node_modules/hubot-2048/src/2048.coffee:368:7, <js>:410:28)
  at TextListener.Listener.call (/Users/sander/dev/florriebot/node_modules/hubot/src/listener.coffee:43:7, <js>:37:14)
  at Robot.receive (/Users/sander/dev/florriebot/node_modules/hubot/src/robot.coffee:230:9, <js>:154:33)
  at Shell.Adapter.receive (/Users/sander/dev/florriebot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/Users/sander/dev/florriebot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:764:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)

Florrie> [Thu Jun 18 2015 11:22:13 GMT+0200 (CEST)] ERROR TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Brain.<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot-redis-brain/src/redis-brain.coffee:75:5, <js>:61:56)
  at Brain.emit (events.js:95:17)
  at Brain.save (/Users/sander/dev/florriebot/node_modules/hubot/src/brain.coffee:54:5, <js>:52:19)
  at [object Object].<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot/src/brain.coffee:80:7, <js>:72:24)
  at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)


/Users/sander/dev/florriebot/node_modules/hubot-redis-brain/src/redis-brain.coffee:61
      return client.set("" + prefix + ":storage", JSON.stringify(data));
                                                       ^
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Brain.<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot-redis-brain/src/redis-brain.coffee:75:5, <js>:61:56)
  at Brain.emit (events.js:95:17)
  at Brain.save (/Users/sander/dev/florriebot/node_modules/hubot/src/brain.coffee:54:5, <js>:52:19)
  at Brain.close (/Users/sander/dev/florriebot/node_modules/hubot/src/brain.coffee:61:5, <js>:57:12)
  at Robot.shutdown (/Users/sander/dev/florriebot/node_modules/hubot/src/robot.coffee:494:5, <js>:424:25)
  at Shell.shutdown (/Users/sander/dev/florriebot/node_modules/hubot/src/adapters/shell.coffee:38:5, <js>:77:18)
  at [object Object].<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot/src/adapters/shell.coffee:76:10, <js>:131:24)
  at [object Object].emit (events.js:92:17)
  at Interface.<anonymous> (/Users/sander/dev/florriebot/node_modules/hubot/node_modules/cline/index.js:143:14)
  at Interface.g (events.js:180:16)
  at Interface.emit (events.js:11%
```

**Comment by malonehedges** [comment]
@whyjustin bump
